#!/bin/zsh

killall sleep.sh

swayidle -w \
         timeout 600 'sh /home/lptlv/.config/scripts/screenlock' \
      #  timeout 60 'qs -c noctalia-shell ipc call lockScreen toggle' \
         timeout 1200 'systemctl suspend' \
         before-sleep 'playerctl pause' \
         before-sleep 'sh /home/lptlv/.config/scripts/screenlock'
