#! /bin/sh

#AUTOSTART

sxhkd -c /home/lptlv/.config/sxhkd/sxhkdrc &
feh --bg-scale /home/lptlv/Pictures/Wallpapers/forest.png
/home/lptlv/.config/polybar/launch.sh &

#picom
picom -b &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap           6
bspc config active_border_color  "#a7c080"
bspc config focused_border_color "#d3c6aa"
bspc config normal_border_color  "#a7c080"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
