#!/bin/zsh

case "$(printf "River - init\nRiver - startup\nRiver - env\nRiver - rules\nWaybar - bar\nWaybar - look\n" | wofi --dmenu -i -H 270 -W 250 -x 0 -y 350 )" in
     'River - init') alacritty -e vim /home/lptlv/.config/river/init;;
     'River - startup') alacritty -e vim /home/lptlv/.config/river/startup;;
     'River - env') alacritty -e vim /home/lptlv/.config/river/environment;;
     'River - rules') alacritty -e vim /home/lptlv/.config/river/windowrules;;
     'Waybar - bar') alacritty -e vim /home/lptlv/.config/waybar/config;;
     'Waybar - look') alacritty -e vim /home/lptlv/.config/waybar/style.css;;
     *) exit 1;;
esac
