#!/bin/zsh

# Keyboard & Touchpad
riverctl keyboard-layout it
riverctl set-repeat 50 200

riverctl input pointer-1739-52861-SYNA32B9:00_06CB:CE7D_Touchpad tap enabled
riverctl input pointer-1739-52861-SYNA32B9:00_06CB:CE7D_Touchpad disable-while-typing enabled
riverctl input pointer-1739-52861-SYNA32B9:00_06CB:CE7D_Touchpad natural-scroll enabled

# Other
