#!/bin/zsh
# Other files
source ~/.config/river/startup
source ~/.config/river/environment
source ~/.config/river/windowrules
source ~/.config/river/hardware

# Terminal
riverctl map normal Super Return spawn alacritty

# Dmenu
riverctl map normal Super Space spawn "wofi --show drun --allow-images"
riverctl map normal Super KP_Insert spawn "wofi --show drun --allow-images"

# Close & reload
riverctl map normal Super Backspace close
riverctl map normal Super+Shift R spawn ~/.config/river/init

# Powermenu
riverctl map normal Super+Shift E spawn "sh /home/lptlv/.config/river/scripts/powermenu.sh"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Right focus-view next
riverctl map normal Super Left focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift Right swap next
riverctl map normal Super+Shift Left swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift Left resize horizontal -50
riverctl map normal Super+Alt+Shift Up resize vertical 50
riverctl map normal Super+Alt+Shift Down resize vertical -50
riverctl map normal Super+Alt+Shift Right resize horizontal 50

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Tab spawn "river-shifttags --occupied"
riverctl map normal Super+Shift Tab spawn "river-shifttags --shifts -1 --occupied"

riverctl map normal Super KP_End set-focused-tags 1
riverctl map normal Super KP_Down set-focused-tags 2
riverctl map normal Super KP_Next set-focused-tags 4
riverctl map normal Super KP_Left set-focused-tags 8
riverctl map normal Super KP_Begin set-focused-tags 16
riverctl map normal Super KP_Right set-focused-tags 32
riverctl map normal Super KP_Home set-focused-tags 64
riverctl map normal Super KP_Up set-focused-tags 128

riverctl map normal Super+Shift KP_End set-view-tags 1
riverctl map normal Super+Shift KP_Down set-view-tags 2
riverctl map normal Super+Shift KP_Next set-view-tags 4
riverctl map normal Super+Shift KP_Left set-view-tags 8
riverctl map normal Super+Shift KP_Begin set-view-tags 16
riverctl map normal Super+Shift KP_Right set-view-tags 32
riverctl map normal Super+Shift KP_Home set-view-tags 64
riverctl map normal Super+Shift KP_Up set-view-tags 128

riverctl map normal Super+Control KP_End toggle-focused-tags 1
riverctl map normal Super+Control KP_Down toggle-focused-tags 2
riverctl map normal Super+Control KP_Next toggle-focused-tags 4
riverctl map normal Super+Control KP_Left toggle-focused-tags 8
riverctl map normal Super+Control KP_Begin toggle-focused-tags 16
riverctl map normal Super+Control KP_Right toggle-focused-tags 32
riverctl map normal Super+Control KP_Home toggle-focused-tags 64
riverctl map normal Super+Control KP_Up toggle-focused-tags 128

# Super+Space to toggle float
riverctl map normal Super+Shift F toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Control Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Control Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Control Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Control Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Calculator, screenshot
riverctl map normal None Print spawn 'grim -g "$(slurp)" "$(xdg-user-dir PICTURES)/Screenshots/$(date +'%y%m%d-%H%M%S').png" && notify-send -t 1000 "Screenshot taken!"'
riverctl map normal None XF86Calculator spawn qalculate-qt

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xd699b6
riverctl border-color-unfocused 0x272e33

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 4 &
