#!/bin/zsh

# Bar
riverctl rule-add -app-id "bar" csd

# Floaty
riverctl rule-add -title "Picture-in-Picture" float
riverctl rule-add -title "Picture-in-Picture" dimensions 480 270
riverctl rule-add -app-id "float*" float
riverctl rule-add -app-id "*ruby*" float
riverctl rule-add -app-id "*YaST*" float
riverctl rule-add -title "*xdg-su*" float
riverctl rule-add -app-id "*xterm*" float
riverctl rule-add -title "*Weiss*" float

# Tags
riverctl rule-add -app-id "*office*" -app-id "*emacs*" tags 2

riverctl rule-add -app-id "*krusader*" tags 4
riverctl rule-add -app-id "*floorp*" tags 8

riverctl rule-add -app-id "*torrent*" tags 16
riverctl rule-add title "Virtual Machine Manager" tags 16

riverctl rule-add -app-id "*cord*" tags 32

riverctl rule-add -title "*Steam" tags 64

riverctl rule-add -title "*ube Mu*" tags 128
